let CARDS=[];let custom={};let selected=[];let known=new Set();let review=new Set();let missCounts={};let deck=[];let pos=0;let flipped=false;let editing=null;
const K={custom:'medCustomGroups',selected:'medSelectedGroups',known:'medKnown',review:'medReview',miss:'medMissCounts',migrated:'medGroups423',dark:'flashcardsDarkMode'};
function esc(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function applyDarkMode(on){document.documentElement.classList.toggle('dark',on);const toggle=document.getElementById('darkModeToggle');if(toggle)toggle.checked=on;const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.setAttribute('content',on?'#0f172a':'#2563eb')}
function setDarkMode(on){localStorage.setItem(K.dark,on?'1':'0');applyDarkMode(on)}
function loadState(){custom=JSON.parse(localStorage.getItem(K.custom)||'{}');selected=JSON.parse(localStorage.getItem(K.selected)||'["All"]');known=new Set(JSON.parse(localStorage.getItem(K.known)||'[]'));review=new Set(JSON.parse(localStorage.getItem(K.review)||'[]'));missCounts=JSON.parse(localStorage.getItem(K.miss)||'{}');applyDarkMode(localStorage.getItem(K.dark)==='1')}
function saveState(){localStorage.setItem(K.custom,JSON.stringify(custom));localStorage.setItem(K.selected,JSON.stringify(selected));localStorage.setItem(K.known,JSON.stringify([...known]));localStorage.setItem(K.review,JSON.stringify([...review]));localStorage.setItem(K.miss,JSON.stringify(missCounts))}
async function loadCards(){const html=await fetch('./index.html?db=v424',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('database');return r.text()});const startMarker='const CARDS=';const endMarker='const DEFAULT_GROUPS';const start=html.indexOf(startMarker);const end=html.indexOf(endMarker,start+startMarker.length);if(start<0||end<0)throw new Error('database markers missing');let raw=html.slice(start+startMarker.length,end).trim();if(raw.endsWith(';'))raw=raw.slice(0,-1).trim();const parsed=JSON.parse(raw);if(!Array.isArray(parsed)||!parsed.length)throw new Error('database empty');CARDS=parsed.filter(c=>c&&c.term&&c.meaning)}
function seedGroups(){if(localStorage.getItem(K.migrated))return;const prefixes=CARDS.map((c,i)=>c.term.endsWith('-')?i:-1).filter(i=>i>=0),suffixes=CARDS.map((c,i)=>c.term.startsWith('-')?i:-1).filter(i=>i>=0),roots=CARDS.map((c,i)=>(!c.term.startsWith('-')&&!c.term.endsWith('-'))?i:-1).filter(i=>i>=0);if(!custom['Likely prefixes'])custom['Likely prefixes']=prefixes;if(!custom['Likely suffixes'])custom['Likely suffixes']=suffixes;if(!custom['Roots / combining forms'])custom['Roots / combining forms']=roots;selected=selected.map(g=>g==='All cards'?'All':g);if(!selected.length)selected=['All'];localStorage.setItem(K.migrated,'1');saveState()}
function allGroups(){return {'All':CARDS.map((_,i)=>i),...custom}}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function buildDeck(){const status=document.getElementById('statusFilter').value;const groups=allGroups();const ids=new Set();selected.forEach(g=>(groups[g]||[]).forEach(i=>ids.add(i)));deck=[...ids].filter(i=>{const t=CARDS[i].term;return status==='all'||(status==='review'&&review.has(t))||(status==='known'&&known.has(t))||(status==='unmarked'&&!known.has(t)&&!review.has(t))||(status==='missed'&&(missCounts[t]||0)>0)});if(status==='missed')deck.sort((a,b)=>(missCounts[CARDS[b].term]||0)-(missCounts[CARDS[a].term]||0));else shuffle(deck);pos=0;flipped=false;renderToolbarGroups();renderCard()}
function directionLabel(){return document.getElementById('direction').value==='term'?'Term':'Meaning'}
function statusLabel(){const v=document.getElementById('statusFilter').value;return {all:'All statuses',review:'Review only',known:'Known only',unmarked:'Unmarked only',missed:'Missed most often'}[v]||'All statuses'}
function renderSummary(){const a=document.getElementById('summaryLine1'),b=document.getElementById('summaryLine2');if(a)a.textContent=directionLabel()+' | '+statusLabel();if(b)b.textContent=deck.length+' cards | '+selected.join(', ');const t=document.getElementById('directionToggle');if(t)t.textContent=directionLabel()}
function closeMenus(){document.querySelectorAll('.tool-menu').forEach(m=>m.classList.add('hidden'))}
function toggleMenu(id,e){if(e)e.stopPropagation();const m=document.getElementById(id);const opening=m.classList.contains('hidden');closeMenus();if(opening)m.classList.remove('hidden')}
function toggleDirection(){const d=document.getElementById('direction');d.value=d.value==='term'?'meaning':'term';flipped=false;renderCard()}
function setStatus(v){document.getElementById('statusFilter').value=v;buildDeck();closeMenus()}
function renderToolbarGroups(){const root=document.getElementById('toolbarGroups');if(!root)return;root.innerHTML='';Object.entries(allGroups()).forEach(([g,ids])=>{const row=document.createElement('label');row.className='menu-check';row.innerHTML='<input type="checkbox" '+(selected.includes(g)?'checked':'')+'><span>'+esc(g)+'</span><small>'+ids.length+'</small>';row.querySelector('input').onchange=()=>toggleGroup(g);root.appendChild(row)});renderSummary()}
function toggleGroup(g){if(g==='All'){selected=['All']}else{selected=selected.filter(x=>x!=='All');selected=selected.includes(g)?selected.filter(x=>x!==g):[...selected,g];if(!selected.length)selected=['All']}saveState();buildDeck()}
function renderCard(){const card=document.getElementById('card');document.getElementById('known').textContent=known.size;document.getElementById('review').textContent=review.size;renderSummary();if(!deck.length){document.getElementById('front').innerHTML='<div class="card-label">No cards</div><div class="card-center"><div class="meaning">Choose different groups or status.</div></div>';document.getElementById('back').innerHTML='';document.getElementById('count').textContent='0 cards';document.getElementById('pct').textContent='';document.getElementById('progress').style.width='0%';card.classList.remove('flipped');return}if(pos>=deck.length)pos=0;if(pos<0)pos=deck.length-1;const c=CARDS[deck[pos]],dir=document.getElementById('direction').value;if(dir==='term'){document.getElementById('front').innerHTML='<div class="card-label">Term</div><div class="card-center"><div class="term">'+esc(c.term)+'</div></div>';document.getElementById('back').innerHTML='<div class="card-label">Meaning</div><div class="card-center"><div class="meaning">'+esc(c.meaning)+'</div><div class="answer-context">'+esc(c.term)+'</div></div>'}else{document.getElementById('front').innerHTML='<div class="card-label">Meaning</div><div class="card-center"><div class="meaning">'+esc(c.meaning)+'</div></div>';document.getElementById('back').innerHTML='<div class="card-label">Term</div><div class="card-center"><div class="term">'+esc(c.term)+'</div><div class="answer-context">'+esc(c.meaning)+'</div></div>'}card.classList.toggle('flipped',flipped);document.getElementById('count').textContent='Card '+(pos+1)+' of '+deck.length;document.getElementById('pct').textContent=Math.round((pos+1)/deck.length*100)+'%';document.getElementById('progress').style.width=((pos+1)/deck.length*100)+'%'}
function flipCard(){flipped=!flipped;renderCard()}function nextCard(){pos++;flipped=false;renderCard()}function prevCard(){pos--;flipped=false;renderCard()}
function markCard(ok){if(!deck.length)return;const t=CARDS[deck[pos]].term;if(ok){known.add(t);review.delete(t)}else{review.add(t);known.delete(t);missCounts[t]=(missCounts[t]||0)+1}saveState();if(document.getElementById('statusFilter').value==='all')nextCard();else buildDeck()}
function groupMastery(ids){if(!ids.length)return 0;return Math.round(ids.filter(i=>known.has(CARDS[i].term)).length/ids.length*100)}
function showGroups(){closeMenus();renderGroups();applyDarkMode(localStorage.getItem(K.dark)==='1');document.getElementById('studyView').classList.add('hidden');document.getElementById('groupsView').classList.remove('hidden');window.scrollTo(0,0)}function showStudy(){document.getElementById('groupsView').classList.add('hidden');document.getElementById('studyView').classList.remove('hidden');buildDeck();window.scrollTo(0,0)}
function renderGroups(){const root=document.getElementById('groupsList');if(!root)return;root.innerHTML='';Object.entries(allGroups()).forEach(([g,ids])=>{const row=document.createElement('div');row.className='check';if(g==='All'){row.innerHTML='<div class="group-name">All<span class="group-meta">'+ids.length+' cards · '+groupMastery(ids)+'% mastery · fixed</span></div>'}else{row.innerHTML='<div class="group-name">'+esc(g)+'<span class="group-meta">'+ids.length+' cards · '+groupMastery(ids)+'% mastery</span></div><button class="edit-link">Edit</button><button class="danger">Delete</button>';const buttons=row.querySelectorAll('button');buttons[0].onclick=()=>renderEditor(g);buttons[1].onclick=()=>deleteGroup(g)}root.appendChild(row)})}
function deleteGroup(g){if(g==='All')return;delete custom[g];selected=selected.filter(x=>x!==g);if(!selected.length)selected=['All'];if(editing===g){editing=null;document.getElementById('groupEditor').innerHTML=''}saveState();renderGroups();buildDeck()}
function createGroup(){const input=document.getElementById('newGroup');const name=input.value.trim();if(!name||name==='All'||allGroups()[name])return;custom[name]=[];input.value='';saveState();renderGroups();renderEditor(name);renderToolbarGroups()}
function renameGroup(oldName,newName){newName=newName.trim();if(!newName||newName==='All'||(newName!==oldName&&allGroups()[newName]))return false;custom[newName]=custom[oldName]||[];if(newName!==oldName)delete custom[oldName];selected=selected.map(g=>g===oldName?newName:g);editing=newName;saveState();renderGroups();renderToolbarGroups();return true}
function renderEditor(name){if(name==='All')return;editing=name;const root=document.getElementById('groupEditor');root.innerHTML='<h2 style="margin-top:18px">Edit group</h2><label>Group name</label><div class="row"><input id="editGroupName" value="'+esc(name)+'"><button onclick="saveGroupName()">Rename</button></div><div class="field"><label>Terms in group</label><input id="groupSearch" placeholder="Search terms to add..." oninput="renderEditorCards()"><div class="checklist" id="editorCards"></div></div>';renderEditorCards();root.scrollIntoView({behavior:'smooth',block:'start'})}
function saveGroupName(){const input=document.getElementById('editGroupName');if(!renameGroup(editing,input.value))alert('Choose a unique group name other than All.');else renderEditor(editing)}
function renderEditorCards(){if(!editing||editing==='All')return;const q=document.getElementById('groupSearch').value.toLowerCase().trim();const set=new Set(custom[editing]||[]);const root=document.getElementById('editorCards');root.innerHTML='';CARDS.forEach((c,i)=>{if(q&&!((c.term+' '+c.meaning).toLowerCase().includes(q)))return;const row=document.createElement('label');row.className='check';row.innerHTML='<input type="checkbox" '+(set.has(i)?'checked':'')+'><div class="group-name">'+esc(c.term)+'<span class="group-meta">'+esc(c.meaning)+'</span></div>';row.querySelector('input').onchange=e=>{e.target.checked?set.add(i):set.delete(i);custom[editing]=[...set];saveState();renderGroups();renderToolbarGroups()};root.appendChild(row)})}
async function exportProgress(){const backup={app:'Flashcards',library:'medical terms',version:'4.2.4',exportedAt:new Date().toISOString(),customGroups:custom,selectedGroups:selected,known:[...known],review:[...review],missCounts,darkMode:localStorage.getItem(K.dark)==='1'};const blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'});const name='flashcards-medical-terms-progress-'+new Date().toISOString().slice(0,10)+'.json';const file=new File([blob],name,{type:'application/json'});if(navigator.canShare&&navigator.canShare({files:[file]})){try{await navigator.share({title:'Flashcards Backup',files:[file]});return}catch(e){if(e.name==='AbortError')return}}const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function importProgress(event){const file=event.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!data||(!data.customGroups&&!data.known&&!data.review))throw 0;custom=data.customGroups||{};selected=(data.selectedGroups||['All']).map(g=>g==='All cards'?'All':g);known=new Set(data.known||[]);review=new Set(data.review||[]);missCounts=data.missCounts||{};if(typeof data.darkMode==='boolean')localStorage.setItem(K.dark,data.darkMode?'1':'0');saveState();applyDarkMode(localStorage.getItem(K.dark)==='1');alert('Progress restored successfully.');renderGroups();buildDeck()}catch{alert('That file is not a valid Flashcards backup.')}finally{event.target.value=''}}
document.addEventListener('click',e=>{if(!e.target.closest('.tool'))closeMenus()});document.addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;if(e.key==='Escape')closeMenus();else if(e.key===' '){e.preventDefault();flipCard()}else if(e.key==='ArrowRight')nextCard();else if(e.key==='ArrowLeft')prevCard();else if(e.key.toLowerCase()==='k')markCard(true);else if(e.key.toLowerCase()==='r')markCard(false)});
(async()=>{loadState();try{await loadCards();seedGroups();buildDeck();renderGroups();applyDarkMode(localStorage.getItem(K.dark)==='1')}catch(e){document.getElementById('front').innerHTML='<div class="meaning">Could not load terms. Refresh once while online.</div>';console.error(e)}})();